on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: smolino/docker-actionv2
        with:
          who-to-greet: 'smolino'
      # Use the output from the `hello` step
      - name: Get the output time
